
export interface Emoji {
  symbol: string;
  label: string;
}

export const EMOJIS: Emoji[] = [
  // Original Emojis
  { symbol: '😀', label: 'Grinning Face' },
  { symbol: '😂', label: 'Face with Tears of Joy' },
  { symbol: '😍', label: 'Smiling Face with Heart-Eyes' },
  { symbol: '🤔', label: 'Thinking Face' },
  { symbol: '👍', label: 'Thumbs Up' },
  { symbol: '👎', label: 'Thumbs Down' },
  { symbol: '🎉', label: 'Party Popper' },
  { symbol: '🚀', label: 'Rocket' },
  { symbol: '💡', label: 'Light Bulb' },
  { symbol: '🐛', label: 'Bug' },
  { symbol: '✨', label: 'Sparkles' },
  { symbol: '🔥', label: 'Fire' },
  { symbol: '💻', label: 'Laptop' },
  { symbol: '📝', label: 'Memo' },
  { symbol: '🔗', label: 'Link Icon' },
  { symbol: '✅', label: 'Check Mark' },
  { symbol: '⚠️', label: 'Warning' },
  { symbol: '👇', label: 'Backhand Index Pointing Down' },
  { symbol: '👈', label: 'Backhand Index Pointing Left'},
  { symbol: '👉', label: 'Backhand Index Pointing Right'},
  { symbol: '🔼', label: 'Upwards Button'},
  { symbol: '🔽', label: 'Downwards Button'},

  // New Emojis - Smileys & People
  { symbol: '😊', label: 'Smiling Face with Smiling Eyes' },
  { symbol: '😇', label: 'Smiling Face with Halo' },
  { symbol: '😉', label: 'Winking Face' },
  { symbol: '😋', label: 'Face Savoring Food' },
  { symbol: '😎', label: 'Smiling Face with Sunglasses' },
  { symbol: '😢', label: 'Crying Face' },
  { symbol: '😭', label: 'Loudly Crying Face' },
  { symbol: '😠', label: 'Angry Face' },
  { symbol: '🥳', label: 'Partying Face' },
  { symbol: '🤯', label: 'Exploding Head' },
  { symbol: '🥱', label: 'Yawning Face' },
  { symbol: '🤫', label: 'Shushing Face' },
  { symbol: '🤝', label: 'Handshake' },
  { symbol: '👋', label: 'Waving Hand' },
  { symbol: '👌', label: 'OK Hand' },
  { symbol: '🙏', label: 'Folded Hands' },
  { symbol: '💪', label: 'Flexed Biceps' },
  { symbol: '🧑‍💻', label: 'Technologist' },
  { symbol: '🧑‍🔬', label: 'Scientist' },
  { symbol: '🧑‍🎨', label: 'Artist' },
  { symbol: '🧑‍🚀', label: 'Astronaut' },

  // New Emojis - Animals & Nature
  { symbol: '🐶', label: 'Dog Face' },
  { symbol: '🐱', label: 'Cat Face' },
  { symbol: '🐭', label: 'Mouse Face' },
  { symbol: '🦊', label: 'Fox Face' },
  { symbol: '🐼', label: 'Panda Face' },
  { symbol: '🦁', label: 'Lion Face' },
  { symbol: '🦄', label: 'Unicorn Face' },
  { symbol: '🌿', label: 'Herb' },
  { symbol: '🍀', label: 'Clover' },
  { symbol: '🌸', label: 'Cherry Blossom' },
  { symbol: '🌻', label: 'Sunflower' },
  { symbol: '🌍', label: 'Globe Showing Europe-Africa' },

  // New Emojis - Food & Drink
  { symbol: '🍎', label: 'Red Apple' },
  { symbol: '🍕', label: 'Pizza Slice' },
  { symbol: '🍔', label: 'Hamburger' },
  { symbol: '🍟', label: 'French Fries' },
  { symbol: '🍦', label: 'Soft Ice Cream' },
  { symbol: '🍩', label: 'Doughnut' },
  { symbol: '☕', label: 'Hot Beverage' },
  { symbol: '🍹', label: 'Tropical Drink' },
  { symbol: '🎂', label: 'Birthday Cake' },

  // New Emojis - Activity & Sports
  { symbol: '⚽', label: 'Soccer Ball' },
  { symbol: '🏀', label: 'Basketball' },
  { symbol: '🏈', label: 'American Football' },
  { symbol: '⚾', label: 'Baseball' },
  { symbol: '🎾', label: 'Tennis Ball' },
  { symbol: '🏆', label: 'Trophy' },
  { symbol: '🎯', label: 'Direct Hit (Dart)' },
  { symbol: '🎮', label: 'Video Game Controller' },
  { symbol: '🎨', label: 'Artist Palette' },
  { symbol: '🎬', label: 'Clapper Board' },
  { symbol: '🎤', label: 'Microphone' },
  { symbol: '🎧', label: 'Headphone' },
  { symbol: '🎼', label: 'Musical Score' },

  // New Emojis - Travel & Places
  { symbol: '✈️', label: 'Airplane' },
  { symbol: '🚢', label: 'Ship' },
  { symbol: '🚗', label: 'Car' },
  { symbol: '🏠', label: 'House' },
  { symbol: '🏥', label: 'Hospital' },
  { symbol: '🏦', label: 'Bank' },
  { symbol: '🏪', label: 'Convenience Store' },
  { symbol: '🗽', label: 'Statue of Liberty' },
  { symbol: '🗺️', label: 'World Map' },

  // New Emojis - Objects
  { symbol: '📞', label: 'Telephone Receiver' },
  { symbol: '💡', label: 'Light Bulb' }, // Duplicate from original, but good to ensure it's here
  { symbol: '💰', label: 'Money Bag' },
  { symbol: '💎', label: 'Gem Stone' },
  { symbol: '🔧', label: 'Wrench' },
  { symbol: '🔨', label: 'Hammer' },
  { symbol: '🔑', label: 'Key' },
  { symbol: '🔒', label: 'Locked' },
  { symbol: '🔔', label: 'Bell' },
  { symbol: '📚', label: 'Books' },
  { symbol: '📖', label: 'Open Book' },
  { symbol: '📰', label: 'Newspaper' },
  { symbol: '🎁', label: 'Wrapped Gift' },
  { symbol: '📈', label: 'Chart Increasing' },
  { symbol: '📉', label: 'Chart Decreasing' },
  { symbol: '📊', label: 'Bar Chart' },
  { symbol: '📌', label: 'Pushpin' },
  { symbol: '📎', label: 'Paperclip' },

  // New Emojis - Symbols
  { symbol: '❤️', label: 'Red Heart' },
  { symbol: '💔', label: 'Broken Heart' },
  { symbol: '💯', label: 'Hundred Points' },
  { symbol: '❓', label: 'Question Mark' },
  { symbol: '❗', label: 'Exclamation Mark' },
  { symbol: '➕', label: 'Plus Sign' },
  { symbol: '➖', label: 'Minus Sign' },
  { symbol: '✖️', label: 'Multiplication Sign' },
  { symbol: '➗', label: 'Division Sign' },
  { symbol: '©️', label: 'Copyright' },
  { symbol: '®️', label: 'Registered' },
  { symbol: '™️', label: 'Trade Mark' },
  { symbol: '♻️', label: 'Recycling Symbol' },
  { symbol: '☢️', label: 'Radioactive' },
  { symbol: '☣️', label: 'Biohazard' },
  { symbol: '☮️', label: 'Peace Symbol' },
  { symbol: '✡️', label: 'Star of David' },
  { symbol: '☪️', label: 'Star and Crescent' },
  { symbol: '☯️', label: 'Yin Yang' },
];
